[tool.poetry]
name = "Cthulhu"
version = "0.0.1"
description = "CMS/ERP sobre Python-AppBuilder"
authors = ["Mario Hernandez <yo@mariofix.com>"]

[tool.poetry.dependencies]
python = "^3.7"
python-dotenv = "^0.14.0"
Flask-AppBuilder = "^3.1.1"
python3-openid = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
